- name: Reboot Server
  reboot:

- name: Restart CRI-O service
  service:
    name: crio
    state: restarted
    enabled: true

- name: Restart NetworkManager
  service:
    name: NetworkManager
    state: restarted
    enabled: true

- name: Reload sysctl
  ansible.builtin.command: sysctl --system
  tags: network
